services:
  - name: app
    type: web
    env: docker
    buildCommand: docker build -t app .
    startCommand: docker run app
    envVars:
      - key: RAILS_ENV
        value: development
      - key: DATABASE_USER
        value: postgres
      - key: DATABASE_PASS
        value: postgres
      - key: DATABASE_HOST
        value: database
      - key: DATABASE_NAME
        value: providers_db
      - key: HOST
        value: api-rest-provider.onrender.com
      - key: SETUP_DB
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
    dependsOn:
      - service: database
        condition: healthy
  - name: database
    type: database
    env: postgres
    plan: starter