default: &default
 adapter: postgresql
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 host: postgres://provider:qaWlC3hexA7pfXRSGXto3nbnBs3qkWyN@dpg-ckpfur8ujous73dhm8p0-a.oregon-postgres.render.com/provider_db
 username: provider
 password: qaWlC3hexA7pfXRSGXto3nbnBs3qkWyN
 port: 5432
 timeout: 5000

development:
  <<: *default
  database: provider_db

test:
  <<: *default
  database: provider_db

production:
  <<: *default
  database: provider_db