default: &default
 adapter: postgresql
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 host: database
 username: postgres
 password: postgres
 port: 5432
 timeout: 5000

development:
  <<: *default
  database: providers_db

#test:
#  <<: *default
#  database: test_db
#
#production:
#  <<: *default
#  database: prod_db